# Generated by Django 4.2.10 on 2024-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codingnotes", "0005_alter_notes_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes", name="body", field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="notes",
            name="tags",
            field=models.ManyToManyField(to="codingnotes.contenttag"),
        ),
    ]
