# Generated by Django 4.2.10 on 2024-02-20 06:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codingnotes", "0006_alter_notes_body_alter_notes_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes", name="body", field=ckeditor.fields.RichTextField(),
        ),
    ]
