# Generated by Django 4.2.10 on 2024-02-20 07:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("codingnotes", "0007_alter_notes_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes", name="body", field=tinymce.models.HTMLField(),
        ),
    ]
